# MongoDB???
spring:
  data:
    mongodb:
      uri:  mongodb://root:root@localhost:27017
      database: test

# ??????MongoDB????
# MongoDB???????
#spring.data.mongodb.host=127.0.0.1
# MongoDB???????
#spring.data.mongodb.port=27017
# MongoDB??????
#spring.data.mongodb.authentication-database=admin
# MongoDB?????
#spring.data.mongodb.username=root
# MongoDB?????
#spring.data.mongodb.password=123456
# ???????
#spring.data.mongodb.database=testMongoDB